import 'package:flutter/material.dart';

class ColorsConstant {
  const ColorsConstant._();

  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);
  static const Color transparent = Colors.transparent;
  static const Color gray1 = Color(0xFF333333);
  static const Color gray2 = Color(0xFF4F4F4F);
  static const Color gray3 = Color(0xFF828282);
  static const Color gray4 = Color(0xFFBDBDBD);
  static const Color gray5 = Color(0xFFE0E0E0);
  static const Color gray6 = Color(0xFFF2F2F2);
  static const Color input = Color(0xFFEFF0F6);
  static const Color gray90 = Color(0xFFE5E5E5);
  static const Color diSerria = Color(0xFFDFA367);
  static const Color blueberry = Color(0xFF6B53FF);
  static const Color gray77 = Color(0xFFC4C4C4);
  static const Color facebook = Color(0xFF3B5998);
  static const Color paleOrange = Color(0xFFFFEDDC);
  static const Color label = Color(0xFF6E7191);
  static const Color blue1 = Color(0xFF2F80ED);
  static const Color blueJeans = Color(0xFF5FBDF2);
  static const Color green = Color(0xFF51C337);
  static const Color green1 = Color(0xFFC7F2D9);
  static const Color green2 = Color(0xFF51C337);
  static const Color athensGray = Color(0xFFF0F0F3);
  static const Color whiteSmoke = Color(0xFFF6F6F6);
  static const Color portage = Color(0xFF9088ED);
  static const Color gulfBlue = Color(0xFF2E3A59);
  static const Color nero = Color(0xFF1F1F1F);
  static const Color persianRed = Color(0xFFDB2020);
  static const Color dimGray = Color(0xFF666666);
  static const Color zest = Color(0xFFDC8218);
  static const Color linen = Color(0xFFFFF2E5);
  static const Color similar = Color(0xFF58968B);
  static const Color error = Color(0xFFFF4C4D);
  static const Color brown = Color(0xFFBB9168);
  static const Color brown2 = Color(0xFFC68D55);
  static const Color beehive = Color(0xFFE1B385);
  static const Color whiskey = Color(0xFFD7A16C);
  static const Color desertSand = Color(0xFFEECFB1);
  static const Color beautyBrush = Color(0xFFF3C9C9);
  static const Color placeHolder = Color(0xFFA0A3BD);
  static const Color body = Color(0xFF4E4B66);


  // Color charts
  static const Color roman = Color(0xFFE56262);
  static const Color porsche = Color(0xFFE0B956);
  static const Color malachite = Color(0xFF4B7911);
  static const Color deepSeaGreen = Color(0xFF085845);
  static const Color harmonies = Color(0xFF00B0FB);
  static const Color governorBay = Color(0xFF302DBE);
  static const Color violet = Color(0xFF9C2AB8);

// static const Color background = Color(0xFFFCFCFC);
// static const Color primary = Color(0xFF3D40C6);
// static const Color success = Color(0xFF00CC67);
// static const Color successlight = Color(0xFFF2FFF9);
// static const Color successdark = Color(0xFF00994D);
// static const Color warning = Color(0xFFF9AA33);
// static const Color placeholder = Color(0xFFA0A3BD);
// static const Color offwhite = Color(0xFFFCFCFC);
// static const Color line = Color(0xFFD9DBE9);
// static const Color title = Color(0xFF222B45);
// static const Color ash = Color(0xFF262338);
// static const Color link = Color(0xFF0095FF);
// static const Color ocean = Color(0xFF00BAFF);
// static const Color primaryBG = Color(0xFFF7F2FF);
// static const Color darkmode = Color(0xFFC19CFC);
// static const Color grayscale = Color(0xFFF7F7FC);
// static const Color secondary = Color(0xFF00C7FF);
// static const Color secondarydark = Color(0xFF007099);
// static const Color offblack = Color(0xFF14142B);
// static const Color search = Color(0xFFF7F7FC);
// static const Color star = Color(0xFFFF9D2B);
// static const Color dot = Color(0xFFC5CEE0);
// static const Color review = Color(0xFFEBF7FF);
// static const Color exam = Color(0xFFEDF1F7);
// static const Color successBG = Color(0xFFE5FFF2);
// static const Color offBlack = Color(0xFF14142B);
// static const Color deepSkyBlue = Color(0xFF00C7FF);
// static const Color facebookBG = Color(0xFF4666D5);
// static const Color richBlack = Color(0xFF020202);
// static const Color vampireBlack = Color(0xFF050505);
// static const Color dodgerBlue = Color(0xFF45c7ff);
// static const Color stormGrey = Color(0xFF6E7191);
// static const Color mauve = Color(0xFFC19CFC);
// static const Color purpleHeart = Color(0xFF5F2EEA);
// static const Color magnolia = Color(0xFFF7F2FF);
// static const Color pink = Color(0xFFE359F9);
// static const Color backgroundFavoriteItem = Color(0xFFEEE5FE);
// static const Color light = Color(0xFFEEE5FE);
// static const Color dark = Color(0xFF3C0594);
// static const Color chili = Color(0xFFFF0000);
// static const Color cadetBlue = Color(0xFF60989F);
// static const Color equator = Color(0xFFCA6BE4);
// static const Color backgroundImageProfile = Color(0xFF9cdded);
// static const Color twitter = Color(0xFF1DA1F2);
}
